version: '3'

services:
  app:
    container_name: findmyshops_container
    command: python ./nearbyshops/manage.py runserver 0.0.0.0:8000
    image: geodjango
    volumes: 
      - .:/workspace/src
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db-data: