version: '3'

services:
  app:
    container_name: findmyshops_container
    image: geodjango
    volumes: 
      - .:/workspace/src
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
