version: '3'

services:
  app:
    container_name: findmyshops_container
    command: bash -c "/wait && python ./nearbyshops/manage.py runserver 0.0.0.0:8000"
    image: geodjango
    volumes: 
      - .:/workspace/src
    ports:
      - "8000:8000"
    environment:
      WAIT_HOSTS: db:5432
    depends_on:
      - db
  db:
    build: ./postgis
    volumes:
      - db-data:/var/lib/postgresql
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_DBNAME=gis
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    ports:
      - "5432:5432"
volumes:
  db-data: